apiVersion: apps/v1
kind: Deployment
metadata:
  name: menuitemdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MenuItemListing
  template:
    metadata:
      labels:
        app: MenuItemListing
    spec:
      containers:
      - name: menuitemlisting
        image: pcregistry.azurecr.io/pcrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: pcsn 

---
apiVersion: v1
kind: Service
metadata:
  name: menuitemlisting
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MenuItemListing